### ISSUE TITLE
Add more scenarios

### ISSUE THREAD

**Issue by lcobucci** [azjezz/benchmark-php-routing#1]
We introduced benchmarking on FastRoute some time ago (https://github.com/nikic/FastRoute/blob/master/benchmark/RealLifeExample.php) and have some scenarios which are missing here: invalid route and method not allowed.

I did observe that FastRoute was faster than SF for happy paths but not for `NOT FOUND` or `METHOD NOT ALLOWED`, maybe we get similar results for hacky-routing.

**Comment by azjezz** [comment]
i assume hack-routing will be much slower with 405 due to some code i wrote back in 2019 https://github.com/hhvm/hack-router/commit/cb83d4026c4f8c8fb877aa8ba40465a99b624534, and i didn't put much though in it, but it can be optimized.

**Comment by azjezz** [comment]
however, optimizing this in hack-routing/hack-router would need a complete rewriting to the prefix map, so instead of having dict<Method, PrefixMap<TResponder>>, it would be PrefixMap<(Method, TResponder)>, which allows delgating the method matching to the end, but would also need to cache a list of all supported methods to allow early return for methods that we know are not supported.
